theme: jekyll-theme-minimal
logo: images/Logo_erste_Wahl_lachen.jpg
title: Alpine Ace - Ski App
description: Speichere diese Seite als Bookmark und verfolge unseren Projektstand!

Inhaltsverzeichnis:
  - [Beschrieb](index.md#beschrieb)
  - [Architektur](index.md#architektur)
      - [Backend](index.md#backend)
      - [Frontend](index.md#frontend)   
  - [Funktionen](index.md#funktionen)
  - [Incoming Features](index.md#features)
  - [Contribution](index.md#contribution)